const {onCall,HttpsError}=require('firebase-functions/v2/https');
const {onDocumentCreated}=require('firebase-functions/v2/firestore');
const {initializeApp}=require('firebase-admin/app');
const {getFirestore,FieldValue}=require('firebase-admin/firestore');
initializeApp();
const db=getFirestore();
async function contextUser(uid){const s=await db.doc('users/'+uid).get();if(!s.exists)throw new HttpsError('permission-denied','User profile not found.');return s.data();}
function requireStaff(u){if(!['agent','guide','driver','manager','tour_manager','admin','superadmin','super_admin','platform_owner'].includes(u.role))throw new HttpsError('permission-denied','Staff access required.');}
exports.createSecureBooking=onCall(async request=>{if(!request.auth)throw new HttpsError('unauthenticated','Authentication required.');const u=await contextUser(request.auth.uid);const d=request.data||{};if(d.tenantId!==u.tenantId)throw new HttpsError('permission-denied','Tenant mismatch.');const guests=Number(d.numberOfGuests);const price=Number(d.unitPrice);if(!d.tourId||guests<1||price<0)throw new HttpsError('invalid-argument','Invalid booking data.');const ref=db.collection('bookings').doc();await ref.set({userId:request.auth.uid,tenantId:u.tenantId,tourId:String(d.tourId),tourName:String(d.tourName||''),travelDate:d.travelDate||null,numberOfGuests:guests,unitPrice:price,totalAmount:guests*price,status:'pending',bookingSource:'flutter_app',paymentMethod:String(d.paymentMethod||'MPESA'),createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});return {bookingId:ref.id,status:'pending'};});
exports.updateBookingStatus=onCall(async request=>{if(!request.auth)throw new HttpsError('unauthenticated','Authentication required.');const u=await contextUser(request.auth.uid);requireStaff(u);const d=request.data||{};const ref=db.doc('bookings/'+String(d.bookingId||''));const snap=await ref.get();if(!snap.exists||snap.data().tenantId!==u.tenantId)throw new HttpsError('not-found','Booking not found.');const allowed=['pending','confirmed','cancelled','completed','no_show'];if(!allowed.includes(d.status))throw new HttpsError('invalid-argument','Invalid booking status.');await ref.update({status:d.status,updatedAt:FieldValue.serverTimestamp(),updatedBy:request.auth.uid});return {ok:true};});
exports.auditBookingCreation=onDocumentCreated('bookings/{bookingId}',async event=>{const b=event.data?.data();if(!b)return;await db.collection('auditLogs').add({tenantId:b.tenantId||'',action:'booking.created',resourceId:event.params.bookingId,userId:b.userId||'',source:b.bookingSource||'unknown',createdAt:FieldValue.serverTimestamp()});});
